[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "python", "rust"]

[tools]
dotnet = "latest"
go = "latest"
node = "lts"
ruby = "latest"
rust = "latest"
"npm:@github/copilot-language-server" = "latest"
